routes/web.php
<?php

use App\Http\Controllers\ClientDetailController;
use App\Http\Controllers\EmployeeDetailController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Stripe\StripeClient;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('home');
})->middleware('auth');

// js routes
Route::get('/check-jquery', function(){
    return view('check-jquery-loaded');
});
Route::get('/scroll', function(){
    return view('scroll');
});
Route::get('/disable-right-click', function(){
    return view('disable-right-click');
});
Route::get('/disable-btn', function(){
    return view('form-btn');
});
Route::get('/checkbox-disable', function(){
    return view('checkbox-btn-disable');
});
Route::get('/broken-image', function(){
    return view('broken-image');
});
Route::get('/blink-text', function(){
    return view('blink-text');
});
Route::get('/print', function(){
    return view('print-page');
});
Route::get('/limit', function(){
    return view('limit-character');
});
Route::get('/bold', function(){
    return view('first-word-bold');
});
Route::get('/create-div', function(){
    return view('create-div');
});
Route::get('/move-div', function(){
    return view('move-div');
});
Route::get('/json', function(){
    return view('json');
});
Route::get('/remove-option', function(){
    return view('remove-option');
});

// admin routes
Route::get('/', function(){
    return view('auth.login');
});

Route::group([ 'middleware' => ['role:admin|employee|client']], function() {
    Route::get('settings', function(){
        return view('admin.settings.index');
    });
    Route::get('settings', [SettingController::class, 'index']);
    Route::resource('general-settings', GeneralSettingController::class);
    Route::resource('languages', LanguageController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('projects', ProjectController::class);
    Route::resource('tasks', TaskController::class);
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('employee-details', EmployeeDetailController::class);
    Route::get('/export', [UserController::class, 'export']);

});
Route::group([ 'middleware' => ['role:admin|client|employee']], function() {
    Route::get('index', function(){
        return view('admin.index');
    });
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('projects', ProjectController::class);
    // Route::resource('stripe', StripeController::class);
    Route::get('stripe', [StripeController::class, 'index']);
    Route::post('projects',  [StripeController::class, 'purchase'])->name('projects.purchase');
});
Route::group([ 'middleware' => ['role:admin|client']], function() {
    Route::resource('invoices', InvoiceController::class);
});

app/Models/Role.php
<?php namespace App\Models;

use Illuminate\Support\Facades\DB;
use Trebol\Entrust\EntrustRole;

class Role extends EntrustRole
{
    protected $fillable = ['name', 'display_name', 'description'];

    public function users() {
        return $this->hasMany(User::class, 'role_user');
    }
    public function clients() {
        return $this->hasMany(ClientDetail::class, 'role_user');
    }
    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }
    public static function getRole()
    {
        $records = DB::table('roles')->select('name')->get()->toArray();
        return $records;
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\RoleDataTable;
use App\Models\GeneralSetting;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(RoleDataTable $dataTable)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        return $dataTable->render('admin.roles.index', compact('code'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $permissions = Permission::get();
        return view('admin.roles.create', compact('permissions', 'code'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = Role::create($request->except(['permission','_token']));
        foreach ($request->permission as $roles)
        {
            $role->attachPermission($roles);
        }
        $role->save();
        return redirect('/roles');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $role = Role::find($id);
        $permissions = Permission::get();
        $role_permission = $role->perms()->pluck('id','id')->toArray();
        return view('admin.roles.show', compact('role', 'permissions', 'role_permission', 'code'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $role = Role::find($id);
        $permissions = Permission::get();
        $role_permission = $role->perms()->pluck('id','id')->toArray();
        return view('admin.roles.edit', compact('role', 'permissions', 'role_permission', 'code'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::find($id);
        $role->name = $request->name;
        $role->display_name = $request->display_name;
        $role->description = $request->description;
        $role->save();
        DB::table('permission_role')->where('role_id', $id)->delete();
        foreach ($request->permission as $roles)
        {
            $role->attachPermission($roles);
        }
        return redirect('/roles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::find($id);
        if ($role == 'admin' || 'employee' || 'client') {
            abort(401, $role +'can not be delete');
        }else
        {
            $role->delete();
        }
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.admin')
@section('title')
    Create Role
@endsection
@section('bread-crumb')
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
            <a href="{{ route('roles.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i>{{ __('admin.Go Back') }} </a>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
            <li class="breadcrumb-item active"><a href="{{ route('roles.index') }}">{{ __('admin.Roles') }}</a></li>
            <li class="breadcrumb-item active">{{ __('admin.Create Role') }}</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
@endsection
@section('content')
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- jquery validation -->
          <div class="card card-primary">
            <div class="card-header">
              <h3>{{ __('admin.Create Role') }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="quickForm" method="POST" action="{{ route('roles.store') }}">
                @csrf
              <div class="card-body">
                <div class="form-group">
                  <label for="name">{{ __('admin.Name') }}</label>
                  <input type="text" name="name" class="form-control" id="name" placeholder="Enter name" value="{{ old('name') }}">
                </div>
                <div class="form-group">
                  <label for="name">{{ __('admin.Display Name') }}</label>
                  <input type="text" name="display_name" class="form-control" id="displayname" placeholder="Enter display name" value="{{ old('displayname') }}">
                </div>
                <div>
                    <label for="name"> {{ __('admin.Role') }}{{ __('admin.Description') }}</label>
                    <textarea name="description" id="description" cols="163" rows="5">
                        {{ old('description') }}
                    </textarea>
                </div>
                <div>
                    <label for="permissions">{{ __('admin.Permissions') }}</label>
                    <div>
                        @foreach ($permissions as $permission)
                            <input type="checkbox" name="permission[]" id="permissions" value="{{ $permission->id }}"><label for="permissions">{{ $permission->display_name }}</label>
                        @endforeach
                    </div>
                </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">{{ __('admin.Submit') }}</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
          </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin')
@section('title')
    Edit Role
@endsection
@section('bread-crumb')
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
            <a href="{{ route('roles.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i> {{ __('admin.Go Back') }}</a>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
            <li class="breadcrumb-item active"><a href="{{ route('roles.index') }}">{{ __('admin.Roles') }}</a></li>
            <li class="breadcrumb-item active">{{ __('admin.Edit Role') }}</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
@endsection
@section('content')
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- jquery validation -->
          <div class="card card-primary">
            <div class="card-header">
              <h3>{{ __('admin.Edit Role') }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="quickForm" method="POST" action="{{ route('roles.update', $role->id) }}">
                @csrf
                @method('PUT')
              <div class="card-body">
                <div class="form-group">
                  <label for="name">{{ __('admin.Name') }}</label>
                  <input type="text" name="name" class="form-control" id="name" placeholder="Enter name" value="{{ $role->name }}">
                </div>
                <div class="form-group">
                  <label for="name">{{ __('admin.Display Name') }}</label>
                  <input type="text" name="display_name" class="form-control" id="displayname" placeholder="Enter display name" value="{{ $role->display_name }}">
                </div>
                <div>
                    <label for="name">{{ __('admin.Role') }}{{ __('admin.Description') }} </label>
                    <textarea name="description" id="description" cols="163" rows="5">
                        {{ $role->description }}
                    </textarea>
                </div>
                <div>
                    <label for="permissions">{{ __('admin.Permissions') }}</label>
                    <div>
                        @foreach ($permissions as $permission)
                            <input type="checkbox" {{ in_array($permission->id, $role_permission) ? 'checked' : '' }} name="permission[]" value="{{ $permission->id }}" >
                            <label for="permissions">{{ $permission->display_name }}</label>
                        @endforeach
                    </div>
                </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">{{ __('admin.Submit') }}</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
          </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.admin')
@section('title')
    Roles
@endsection

@section('bread-crumb')
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1>{{ __('admin.Roles List') }}</h1>
            <a href="{{ route('roles.create') }}" class="btn btn-primary"style="margin-left: 210px; margin-top:-50px"><span class="fa fa-plus"></span>{{ __('admin.Add') }}</a>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item">{{ __('admin.Roles List') }}</li>
            <li class="breadcrumb-item active">{{ __('admin.Roles') }}</li>
            </ol>
        </div>
        </div>
    </div><!-- /.container-fluid -->
@endsection

@section('content')
    {!! $dataTable->table() !!}
@endsection

@section('script')

    <script src="{{ asset('assets/plugins/sweetalert2/sweetalert2.min.css') }}"></script>
    {!! $dataTable->scripts() !!}
    <script>

        $(document).ready(function() {

            $('.delete-role').click(function() {

                let roleId = $(this).data('role-id');

                // Generate Token method 1
                // let token = $("meta[name='csrf-token']").attr("content");

                // Generate Token method 2
                let token = '{{ csrf_token() }}';

                let url = '{{ route('roles.destroy', ':id') }}';
                url = url.replace(':id', roleId);

                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this data!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                }, function() {

                    $.ajax({
                        url: url,
                        type: 'POST',
                        data: {
                            "_token": token,
                            "_method": 'DELETE',
                        },
                        success: function() {
                            swal("Deleted!", "Role has been deleted.",
                                "success");
                            setTimeout(() => {
                                location.reload();
                            }, 1000);
                        }
                    });

                });
            });

        });
    </script>
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.admin')
@section('title')
    Show Role
@endsection
@section('bread-crumb')
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
            <a href="{{ route('roles.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i>{{ __('admin.Go Back') }}</a>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
            <li class="breadcrumb-item active"><a href="{{ route('roles.index') }}">{{ __('admin.Roles') }}</a></li>
            <li class="breadcrumb-item active">{{ __('admin.Show Role') }}</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
@endsection
@section('content')
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- jquery validation -->
          <div class="card card-primary">
            <div class="card-header">
              <h3>{{ __('admin.Show Role') }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="quickForm" method="POST" action="{{ route('roles.show', $role->id) }}">
                @csrf
              <div class="card-body">
                <div class="form-group">
                  <label for="name">{{ __('admin.Name') }}</label>
                  <input type="text" name="name" class="form-control" id="name" placeholder="Enter name" value="{{ $role->name }}">
                </div>
                <div class="form-group">
                  <label for="name">{{ __('admin.Display Name') }}</label>
                  <input type="text" name="display_name" class="form-control" id="displayname" placeholder="Enter display name" value="{{ $role->display_name }}">
                </div>
                <div>
                    <label for="name">{{ __('admin.Role') }} {{ __('admin.Description') }}</label>
                    <textarea name="description" id="description" cols="163" rows="5">
                        {{ $role->description }}
                    </textarea>
                </div>
                <div>
                    <label for="permissions">{{ __('admin.Permissions') }}</label>
                    <div>
                        @foreach ($permissions as $permission)
                            <input type="checkbox" {{ in_array($permission->id, $role_permission) ? 'checked' : '' }} name="permission[]" value="{{ $permission->id }}" >
                            <label for="permissions">{{ $permission->display_name }}</label>
                        @endforeach
                    </div>
                </div>
              </div>
              <!-- /.card-body -->
            </form>
          </div>
          <!-- /.card -->
          </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
@endsection