routes/web.php
<?php

use App\Http\Controllers\ClientDetailController;
use App\Http\Controllers\EmployeeDetailController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Stripe\StripeClient;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('home');
})->middleware('auth');

// js routes
Route::get('/check-jquery', function(){
    return view('check-jquery-loaded');
});
Route::get('/scroll', function(){
    return view('scroll');
});
Route::get('/disable-right-click', function(){
    return view('disable-right-click');
});
Route::get('/disable-btn', function(){
    return view('form-btn');
});
Route::get('/checkbox-disable', function(){
    return view('checkbox-btn-disable');
});
Route::get('/broken-image', function(){
    return view('broken-image');
});
Route::get('/blink-text', function(){
    return view('blink-text');
});
Route::get('/print', function(){
    return view('print-page');
});
Route::get('/limit', function(){
    return view('limit-character');
});
Route::get('/bold', function(){
    return view('first-word-bold');
});
Route::get('/create-div', function(){
    return view('create-div');
});
Route::get('/move-div', function(){
    return view('move-div');
});
Route::get('/json', function(){
    return view('json');
});
Route::get('/remove-option', function(){
    return view('remove-option');
});

// admin routes
Route::get('/', function(){
    return view('auth.login');
});

Route::group([ 'middleware' => ['role:admin|employee|client']], function() {
    Route::get('settings', function(){
        return view('admin.settings.index');
    });
    Route::get('settings', [SettingController::class, 'index']);
    Route::resource('general-settings', GeneralSettingController::class);
    Route::resource('languages', LanguageController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('projects', ProjectController::class);
    Route::resource('tasks', TaskController::class);
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('employee-details', EmployeeDetailController::class);
    Route::get('/export', [UserController::class, 'export']);

});
Route::group([ 'middleware' => ['role:admin|client|employee']], function() {
    Route::get('index', function(){
        return view('admin.index');
    });
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('projects', ProjectController::class);
    // Route::resource('stripe', StripeController::class);
    Route::get('stripe', [StripeController::class, 'index']);
    Route::post('projects',  [StripeController::class, 'purchase'])->name('projects.purchase');
});
Route::group([ 'middleware' => ['role:admin|client']], function() {
    Route::resource('invoices', InvoiceController::class);
});

app/Models/Language.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    use HasFactory;
}

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\LanguageDataTable;
use App\Models\GeneralSetting;
use App\Models\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;

class LanguageController extends Controller
{
    public function index(LanguageDataTable $dataTable)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        return $dataTable->render('admin.settings.index', compact('code'));

    }

    public function create()
    {
        return view('dashboard.languages.create');
    }

    public function store(Request $request)
    {
        $language = new Language;
        $language->name = $request->name;
        $language->code = $request->code;
        $language->status = $request->status;
        $path = base_path() . '/resources/lang/' . $request->code;
        if (!file_exists($path)) {
            File::makeDirectory($path, $mode = 0777, true, true);
        }
        $language->save();
        return redirect('/settings');
    }

    public function edit($id)
    {
        $language = Language::find($id);
        return view('admin.settings.index', compact('language'));
    }

    public function update(Request $request, $id)
    {
        $language = Language::find($id);
        $language->name = $request->name;
        $language->code = $request->code;
        $language->status = $request->status;
        $language->save();
        return redirect('/settings');
    }

    public function destroy($id)
    {
        $code = Language::select('code')->where('id',$id )->pluck('code');
        if($code[0] =='en'){
            return redirect('/settings');
        }
        $path = base_path().'/resources/lang/'.$code[0];
        if (file_exists($path)) {
              File::deleteDirectory($path);
          }
        Language::find($id)->delete();
        return redirect('/settings');

    }
}

resources/views/admin/languages/create.blade.php
{{-- @extends('layouts.admin')

@section('content')
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Add Language Form</h2>
        <ol class="breadcrumb">
            <li>
                <a href="/setting-index">Home</a>
            </li>
            <li class="active">fucnti
                <strong>Add Language</strong>

            </li>
        </ol>
    </div>
</div>

<body onload="languageModal()">
    <!-- Modal -->
    <div class="modal fade" id="language" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalLabel">Fill Form</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" class="form-horizontal" action="{{ route('languages.store') }}">
                    <div class="modal-body">
                        @csrf
                        <div class="form-group"><label class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10"><input type="text" class="form-control" name="name"></div>
                        </div>
                        <div class="form-group"><label class="col-sm-2 control-label">Code</label>
                            <div class="col-sm-10"><input type="text" class="form-control" name="code"></div>
                        </div>
                        <div class="form-group"><label class="col-sm-2 control-label">Select</label>
                            <div class="col-sm-10">
                                 <select class="form-control" name="status" id="status">
                                    <option>Select</option>
                                    <option @if(old('status') == 'active') selected @endif value="active">Active</option>
                                    <option  @if(old('status') == 'inactive') selected @endif value="inactive">Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        function languageModal() {
            $('#exampleModal').modal('show');
        }
    </script>
</body>

@endsection --}}
sec-26 ,video-246
roll and permission
sec-38, video-303-309

resources/views/admin/languages/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Add Language Form</h2>
        <ol class="breadcrumb">
            <li>
                <a href="/setting-index">Home</a>
            </li>
            <li class="active">fucnti
                <strong>Add Language</strong>

            </li>
        </ol>
    </div>
</div>

<body onload="languageModal()">
    <!-- Modal -->
    <div class="modal fade" id="editlanguage" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalLabel">Fill Form</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" class="form-horizontal" action="{{ route('languages.update', $language->id) }}">
                    <div class="modal-body">
                        @csrf
                        <div class="form-group"><label class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" value="{{ $language->name }}">
                            </div>
                        </div>
                        <div class="form-group"><label class="col-sm-2 control-label">Code</label>
                            <div class="col-sm-10"><input type="text" class="form-control" name="code" value="{{ $language->code }}"></div>
                        </div>
                        <div class="form-group"><label class="col-sm-2 control-label">Select</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="status" id="status">
                                    <option>Select</option>
                                    <option value="active" {{ $faqs->status == 'active' ? 'selected' : '' }}>
                                        Active</option>
                                    <option value="inactive"
                                        {{ $faqs->status == 'inactive' ? 'selected' : '' }}>Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        function languageModal() {
            $('#exampleModal').modal('show');
        }
    </script>
</body>

@endsection