routes/web.php
<?php

use App\Http\Controllers\ClientDetailController;
use App\Http\Controllers\EmployeeDetailController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Stripe\StripeClient;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('home');
})->middleware('auth');

// js routes
Route::get('/check-jquery', function(){
    return view('check-jquery-loaded');
});
Route::get('/scroll', function(){
    return view('scroll');
});
Route::get('/disable-right-click', function(){
    return view('disable-right-click');
});
Route::get('/disable-btn', function(){
    return view('form-btn');
});
Route::get('/checkbox-disable', function(){
    return view('checkbox-btn-disable');
});
Route::get('/broken-image', function(){
    return view('broken-image');
});
Route::get('/blink-text', function(){
    return view('blink-text');
});
Route::get('/print', function(){
    return view('print-page');
});
Route::get('/limit', function(){
    return view('limit-character');
});
Route::get('/bold', function(){
    return view('first-word-bold');
});
Route::get('/create-div', function(){
    return view('create-div');
});
Route::get('/move-div', function(){
    return view('move-div');
});
Route::get('/json', function(){
    return view('json');
});
Route::get('/remove-option', function(){
    return view('remove-option');
});

// admin routes
Route::get('/', function(){
    return view('auth.login');
});

Route::group([ 'middleware' => ['role:admin|employee|client']], function() {
    Route::get('settings', function(){
        return view('admin.settings.index');
    });
    Route::get('settings', [SettingController::class, 'index']);
    Route::resource('general-settings', GeneralSettingController::class);
    Route::resource('languages', LanguageController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('projects', ProjectController::class);
    Route::resource('tasks', TaskController::class);
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('employee-details', EmployeeDetailController::class);
    Route::get('/export', [UserController::class, 'export']);

});
Route::group([ 'middleware' => ['role:admin|client|employee']], function() {
    Route::get('index', function(){
        return view('admin.index');
    });
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('projects', ProjectController::class);
    // Route::resource('stripe', StripeController::class);
    Route::get('stripe', [StripeController::class, 'index']);
    Route::post('projects',  [StripeController::class, 'purchase'])->name('projects.purchase');
});
Route::group([ 'middleware' => ['role:admin|client']], function() {
    Route::resource('invoices', InvoiceController::class);
});

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    use HasFactory;
    public function users()
    {
        return $this->belongsTo(User::class, 'client_id');
    }
    public function project()
    {
        return $this->belongsTo(Project::class);
    }
    public function setInvoiceDateAttribute($value)
    {
        $this->attributes['invoice_date'] = date('Y-m-d', strtotime($value));
    }
    // Accessor
    public function getInvoiceDateAttribute($value)
    {
        return date('d M, Y', strtotime($value));
    }

    public function setDueDateAttribute($due_date)
    {
        $this->attributes['due_date'] = date('Y-m-d', strtotime($due_date));
    }
    public function getDueDateAttribute($due_date)
    {
        return date('d M, Y', strtotime($due_date));
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\InvoiceDataTable;
use App\Models\GeneralSetting;
use App\Models\Invoice;
use App\Models\Project;
use App\Models\User;
use Illuminate\Support\Facades\Session;

class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(InvoiceDataTable $dataTable)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        return $dataTable->render('admin.invoices.index', compact('code'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $clients = User::whereHas('roles', function($q)
        {
            $q->where('name', 'client');
        })->get();
        $projects = Project::where('status', 'active')->get();
        return view('admin.invoices.create', compact('code', 'clients', 'projects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $invoice = new Invoice();
        $invoice->client_id = $request->client_id;
        $invoice->project_id = $request->project_id;
        $invoice->invoice_date = $request->invoice_date;
        $invoice->due_date = $request->due_date;
        $invoice->save();
        return redirect('/invoices');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $invoice = Invoice::find($id);
        $clients = User::whereHas('roles', function($q)
        {
            $q->where('name', 'client');
        })->get();
        $projects = Project::where('status', 'active')->get();
        return view('admin.invoices.show', compact('code', 'clients', 'projects', 'invoice'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $invoice = Invoice::find($id);
        $clients = User::whereHas('roles', function($q)
        {
            $q->where('name', 'client');
        })->get();
        $projects = Project::where('status', 'active')->get();
        return view('admin.invoices.edit', compact('code', 'clients', 'projects', 'invoice'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $invoice = Invoice::find($id);
        $invoice->client_id = $request->client_id;
        $invoice->project_id = $request->project_id;
        $invoice->invoice_date = $request->invoice_date;
        $invoice->due_date = $request->due_date;
        $invoice->save();
        return redirect('/invoices');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $invoice = Invoice::find($id)->delete();
    }
}

resources/views/admin/invoices/create.blade.php
@extends('layouts.admin')
@section('title')
  Create Invoice
@endsection
@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
@endsection
@section('bread-crumb')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <a href="{{ route('invoices.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i> {{ __('admin.Go Back') }}</a>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
                <li class="breadcrumb-item active"><a href="{{ route('invoices.index') }}">{{ __('admin.Invoices') }}</a></li>
                <li class="breadcrumb-item active">{{ __('admin.Create Invoice') }}</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3>{{ __('admin.Create Invoice') }}</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="quickForm" method="POST" action="{{ route('invoices.store') }}">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        <label>{{ __('admin.Invoice Date') }}</label>
                                        <input type="text" class="form-control datepicker" placeholder="Enter Invoice Date" name="invoice_date" id="invoice_date" autocomplete="off" value="{{ old('invoice_date') }}">
                                        </div>
                                        <div class="form-group ">
                                            <label for="deadline">{{ __('admin.Due Date') }}</label>
                                            <input type="text" class="form-control datepicker" placeholder="Enter Due Date" name="due_date" id="due_date" autocomplete="off" value="{{ old('due_date') }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group ">
                                            <label for="completions">{{ __('admin.Client') }}</label>
                                            <select class="form-control" name="client_id" id="client_id">
                                                <option>{{ __('admin.Select') }}</option>
                                                @foreach ($clients as $client)
                                                    <option value="{{ $client->id }}">{{ $client->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group ">
                                            <label for="client">{{ __('admin.Project') }}</label>
                                            <select class="form-control" name="project_id" id="project_id">
                                                <option>{{ __('admin.Select') }}</option>
                                                @foreach ($projects as $project)
                                                    <option value="{{ $project->id }}">{{ $project->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">{{ __('admin.Submit') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>

        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });
    </script>
@endsection

resources/views/admin/invoices/edit.blade.php
@extends('layouts.admin')
@section('title')
  Edit Invoice
@endsection
@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
@endsection
@section('bread-crumb')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <a href="{{ route('invoices.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i> {{ __('admin.Go Back') }}</a>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
                <li class="breadcrumb-item active"><a href="{{ route('invoices.index') }}">{{ __('admin.Invoices') }}</a></li>
                <li class="breadcrumb-item active">{{ __('admin.Edit Invoice') }}</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3>{{ __('admin.Edit Invoice') }}</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="quickForm" method="POST" action="{{ route('invoices.update', $invoice->id) }}">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        <label>{{ __('admin.Invoice Date') }}</label>
                                        <input type="text" class="form-control datepicker" placeholder="Enter Invoice Date" name="invoice_date" id="invoice_date" autocomplete="off" value="{{ $invoice->invoice_date }}">
                                        </div>
                                        <div class="form-group ">
                                            <label for="deadline">{{ __('admin.Due Date') }}</label>
                                            <input type="text" class="form-control datepicker" placeholder="Enter Due Date" name="due_date" id="due_date" autocomplete="off" value="{{ $invoice->due_date }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group ">
                                            <label for="completions">{{ __('admin.Client') }}</label>
                                            <select class="form-control" name="client_id" id="client_id">
                                                <option>{{ __('admin.Select') }}</option>
                                                @foreach ($clients as $client)
                                                    <option value="{{ $client->id }}"  @if($client->id == $invoice->client_id) selected @endif>{{ $client->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group ">
                                            <label for="client">{{ __('admin.Project') }}</label>
                                            <select class="form-control" name="project_id" id="project_id">
                                                <option>{{ __('admin.Select') }}</option>
                                                @foreach ($projects as $project)
                                                    <option value="{{ $project->id }}" @if($project->id == $invoice->project_id) selected @endif>{{ $project->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">{{ __('admin.Submit') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>

        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });
    </script>
@endsection

resources/views/admin/invoices/index.blade.php
@extends('layouts.admin')
@section('title')
    Invoices
@endsection

@section('bread-crumb')
<div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>{{ __('admin.Invoice List') }}</h1>
        <a href="{{ route('invoices.create') }}"  class="btn btn-primary mt" style="margin-left: 180px; margin-top:-50px"><span class="fa fa-plus"></span>{{ __('admin.Add') }}</a>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
          <li class="breadcrumb-item active">{{ __('admin.Invoice') }}</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
@endsection

@section('content')
    {!! $dataTable->table() !!}
@endsection

@section('script')
    {!! $dataTable->scripts() !!}
<script>

    $(document).ready(function() {

        $('.delete-invoice').click(function() {

            let invoiceId = $(this).data('invoice-id');

            // Generate Token method 1
            // let token = $("meta[name='csrf-token']").attr("content");

            // Generate Token method 2
            let token = '{{ csrf_token() }}';

            let url = '{{ route('invoices.destroy', ':id') }}';
            url = url.replace(':id', invoiceId);

            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this data!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function() {

                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        "_token": token,
                        "_method": 'DELETE',
                    },
                    success: function() {
                        swal("Deleted!", "Invoice has been deleted.",
                            "success");
                        setTimeout(() => {
                            location.reload();
                        }, 1000);
                    }
                });

            });
        });

    });
</script>
@endsection

resources/views/admin/invoices/show.blade.php
@extends('layouts.admin')
@section('title')
  Show Invoice
@endsection
@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
@endsection
@section('bread-crumb')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <a href="{{ route('invoices.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i> {{ __('admin.Go Back') }}</a>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
                <li class="breadcrumb-item active"><a href="{{ route('invoices.index') }}">{{ __('admin.Invoices') }}</a></li>
                <li class="breadcrumb-item active">{{ __('admin.Show Invoice') }}</li>
                </ol>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3>{{ __('admin.Show Invoice') }}</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="quickForm" method="POST" action="{{ route('invoices.show', $invoice->id) }}">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        <label>{{ __('admin.Invoice Date') }}</label>
                                        <input type="text" class="form-control datepicker" placeholder="Enter Invoice Date" name="invoice_date" id="invoice_date" autocomplete="off" value="{{ $invoice->invoice_date }}">
                                        </div>
                                        <div class="form-group ">
                                            <label for="deadline">{{ __('admin.Due Date') }}</label>
                                            <input type="text" class="form-control datepicker" placeholder="Enter Due Date" name="due_date" id="due_date" autocomplete="off" value="{{ $invoice->due_date }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group ">
                                            <label for="completions">{{ __('admin.Client') }}</label>
                                            <select class="form-control" name="client_id" id="client_id">
                                                <option>{{ __('admin.Select') }}</option>
                                                @foreach ($clients as $client)
                                                    <option value="{{ $client->id }}"  @if($client->id == $invoice->client_id) selected @endif>{{ $client->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group ">
                                            <label for="client">{{ __('admin.Project') }}</label>
                                            <select class="form-control" name="project_id" id="project_id">
                                                <option>{{ __('admin.Select') }}</option>
                                                @foreach ($projects as $project)
                                                    <option value="{{ $project->id }}" @if($project->id == $invoice->project_id) selected @endif>{{ $project->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <a href="/stripe" class="btn btn-primary">{{ __('admin.Pay') }}</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>

        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
            startView: 2,
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });
    </script>
@endsection