routes/web.php
<?php

use App\Http\Controllers\ClientDetailController;
use App\Http\Controllers\EmployeeDetailController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use Stripe\StripeClient;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('home');
})->middleware('auth');

// js routes
Route::get('/check-jquery', function(){
    return view('check-jquery-loaded');
});
Route::get('/scroll', function(){
    return view('scroll');
});
Route::get('/disable-right-click', function(){
    return view('disable-right-click');
});
Route::get('/disable-btn', function(){
    return view('form-btn');
});
Route::get('/checkbox-disable', function(){
    return view('checkbox-btn-disable');
});
Route::get('/broken-image', function(){
    return view('broken-image');
});
Route::get('/blink-text', function(){
    return view('blink-text');
});
Route::get('/print', function(){
    return view('print-page');
});
Route::get('/limit', function(){
    return view('limit-character');
});
Route::get('/bold', function(){
    return view('first-word-bold');
});
Route::get('/create-div', function(){
    return view('create-div');
});
Route::get('/move-div', function(){
    return view('move-div');
});
Route::get('/json', function(){
    return view('json');
});
Route::get('/remove-option', function(){
    return view('remove-option');
});

// admin routes
Route::get('/', function(){
    return view('auth.login');
});

Route::group([ 'middleware' => ['role:admin|employee|client']], function() {
    Route::get('settings', function(){
        return view('admin.settings.index');
    });
    Route::get('settings', [SettingController::class, 'index']);
    Route::resource('general-settings', GeneralSettingController::class);
    Route::resource('languages', LanguageController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('projects', ProjectController::class);
    Route::resource('tasks', TaskController::class);
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('employee-details', EmployeeDetailController::class);
    Route::get('/export', [UserController::class, 'export']);

});
Route::group([ 'middleware' => ['role:admin|client|employee']], function() {
    Route::get('index', function(){
        return view('admin.index');
    });
    Route::resource('client-details', ClientDetailController::class);
    Route::resource('projects', ProjectController::class);
    // Route::resource('stripe', StripeController::class);
    Route::get('stripe', [StripeController::class, 'index']);
    Route::post('projects',  [StripeController::class, 'purchase'])->name('projects.purchase');
});
Route::group([ 'middleware' => ['role:admin|client']], function() {
    Route::resource('invoices', InvoiceController::class);
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $fillable = ['id', 'name', 'project_id', 'due_date', 'assigned_to', 'status'];

    public function setDueDateAttribute($value)
    {
        $this->attributes['due_date'] = date('Y-m-d', strtotime($value));
    }

    // Accessor
    public function getDueDateAttribute($value)
    {
        return date('d M, Y', strtotime($value));
    }

    // relation with projects table
    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    // relation with user table
    public function assignedTo()
    {
        return $this->belongsTo(User::class, 'assigned_to', 'id');
    }
  
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\TaskDataTable;
use App\Models\GeneralSetting;
use App\Models\Project;
use App\Models\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(TaskDataTable $taskDataTable)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        return $taskDataTable->render('admin.tasks.index', compact('code'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $projects = Project::with('members')->get();
        foreach ($projects as $key => $project) {
            $members = $project->members;
        }
        return view('admin.tasks.create', compact('projects', 'members', 'code'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $task = new Task;
        $task->name = $request->name;
        $task->assigned_to = $request->assigned_to;
        $task->project_id = $request->project_id;
        $task->due_date = $request->due_date;
        $task->status = $request->status;
        $task->save();
        return redirect('/tasks');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show( $id)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $task = Task::find($id);
        $projects = Project::with('members')->get();
        foreach ($projects as $key => $project) {
            $members = $project->members;
        }
        return view('admin.tasks.show', compact('projects', 'members', 'task', 'code'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $code =  GeneralSetting::where('id', 1)->value('language');
        Session::put('locale',$code);
        app()->setLocale(Session::get('locale'));
        $task = Task::find($id);
        $projects = Project::with('members')->get();
        foreach ($projects as $key => $project) {
            $members = $project->members;
        }
        return view('admin.tasks.edit', compact('projects', 'members', 'task', 'code'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $task = Task::find($id);
        $task->name = $request->name;
        $task->assigned_to = $request->assigned_to;
        $task->project_id = $request->project_id;
        $task->due_date = $request->due_date;
        $task->status = $request->status;
        $task->save();
        return redirect('/tasks');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Task::find($id)->delete();
    }
}

resources/views/admin/tasks/create.blade.php
@extends('layouts.admin')
@section('title')
    Create Task
@endsection
@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection
@section('bread-crumb')
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
            <a href="{{ route('tasks.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i> {{ __('admin.Go Back') }}</a>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
            <li class="breadcrumb-item active"><a href="{{ route('tasks.index') }}">{{ __('admin.Tasks') }}</a></li>
            <li class="breadcrumb-item active">{{ __('admin.Create Task') }}</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
@endsection
@section('content')
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- jquery validation -->
          <div class="card card-primary">
            <div class="card-header">
              <h3>{{ __('admin.Create Task') }} </h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="quickForm" method="POST" action="{{ route('tasks.store') }}">
                @csrf
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name">{{ __('admin.Name') }}</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Enter name" value="{{ old('name') }}">
                            </div>
                            <div class="form-group ">
                                <label for="client">{{ __('admin.Projects') }}</label>
                                <select class="form-control" name="project_id" id="project_id">
                                    @foreach ($projects as $project)
                                        <option value="{{ $project->id }}">{{ $project->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group ">
                                <label for="due_date">{{ __('admin.Due Date') }}</label>
                                <input type="text" class="form-control datepicker" placeholder="Enter Due Date" name="due_date" id="due_date" autocomplete="off" value="{{ old('due_date') }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label for="assigned_to">{{ __('admin.Assigned To') }}</label>
                                <select class="form-control" name="assigned_to" id="assigned_to">
                                    @foreach ($members as $member)
                                        <option value="{{ $member->id }}">{{ $member->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>{{ __('admin.Status') }}</label>
                                <select class="form-control" name="status" id="status">
                                    <option>{{ __('admin.Select') }}</option>
                                    <option @if(old('status') == 'active') selected @endif value="active">{{ __('admin.Active') }}</option>
                                    <option  @if(old('status') == 'inactive') selected @endif value="inactive">{{ __('admin.Inactive') }}</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">{{ __('admin.Submit') }}</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
          </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>

    $('.datepicker').datepicker({
        // format: 'yyyy-mm-dd',
        format: 'dd-mm-yyyy',
        startView: 2,
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true
    });
</script>
@endsection

resources/views/admin/tasks/edit.blade.php
@extends('layouts.admin')
@section('title')
    Edit Task
@endsection
@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection
@section('bread-crumb')
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
            <a href="{{ route('tasks.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i>{{ __('admin.Go Back') }}</a>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
            <li class="breadcrumb-item active"><a href="{{ route('tasks.index') }}">{{ __('admin.Tasks') }}</a></li>
            <li class="breadcrumb-item active">{{ __('admin.Edit Task') }}</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
@endsection
@section('content')
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- jquery validation -->
          <div class="card card-primary">
            <div class="card-header">
              <h3>{{ __('admin.Edit Task') }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="quickForm" method="POST" action="{{ route('tasks.update', $task->id) }}">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="name">{{ __('admin.Name') }}</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Enter name" value="{{ $task->name }}">
                            </div>
                            <div class="form-group ">
                                <label for="client">{{ __('admin.Projects') }}</label>
                                <select class="form-control" name="project_id" id="project_id">
                                    @foreach ($projects as $project)
                                        <option value="{{ $project->id }}" @if($project->id == $task->project_id) selected @endif>{{ $project->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group ">
                                <label for="due_date">{{ __('admin.Due Date') }}</label>
                                <input type="text" class="form-control datepicker" placeholder="Enter Due Date" name="due_date" id="due_date" autocomplete="off" value="{{ $task->due_date }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label for="assigned_to">{{ __('admin.Assigned To') }}</label>
                                <select class="form-control" name="assigned_to" id="assigned_to">
                                    @foreach ($members as $member)
                                        <option value="{{ $member->id }}" @if($member->id == $task->member_id) selected @endif>{{ $member->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>{{ __('admin.Status') }}</label>
                                <select class="form-control" name="status" id="status">
                                    <option>{{ __('admin.Select') }}</option>
                                    <option value="active" {{ $project->status == 'active' ? 'selected' : '' }}>{{ __('admin.Active') }}</option>
                                    <option value="inactive" {{ $project->status == 'inactive' ? 'selected' : '' }}>{{ __('admin.Inactive') }}</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary">{{ __('admin.Submit') }}</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
          </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>

    $('.datepicker').datepicker({
        // format: 'yyyy-mm-dd',
        format: 'dd-mm-yyyy',
        startView: 2,
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true
    });
</script>
@endsection

resources/views/admin/tasks/index.blade.php
@extends('layouts.admin')
@section('title')
    Tasks
@endsection

@section('bread-crumb')
<div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>{{ __('admin.Tasks List') }}</h1>
        <a href="{{ route('tasks.create') }}"  class="btn btn-primary mt" style="margin-left: 150px; margin-top:-50px"><span class="fa fa-plus"></span>{{ __('admin.Add') }}</a>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
          <li class="breadcrumb-item active">{{ __('admin.Tasks') }}</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
@endsection

@section('content')
{!! $dataTable->table() !!}
@endsection

@section('script')
{!! $dataTable->scripts() !!}
<script>
    $(document).ready(function() {

        $('.delete-user').click(function() {

            let userId = $(this).data('user-id');

            // Generate Token method 1
            // let token = $("meta[name='csrf-token']").attr("content");

            // Generate Token method 2
            let token = '{{ csrf_token() }}';

            let url = '{{ route('users.destroy', ':id') }}';
            url = url.replace(':id', userId);

            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this data!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function() {

                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        "_token": token,
                        "_method": 'DELETE',
                    },
                    success: function() {
                        swal("Deleted!", "User has been deleted.",
                            "success");
                        setTimeout(() => {
                            location.reload();
                        }, 1000);
                    }
                });

            });
        });

    });
</script>
@endsection

resources/views/admin/tasks/show.blade.php
@extends('layouts.admin')
@section('title')
    Show Task
@endsection
@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection
@section('bread-crumb')
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
            <a href="{{ route('tasks.index') }}" class="btn btn-warning"><i class="nav-icon fas fa-arrow-left"></i>{{ __('admin.Go Back') }}</a>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('admin.Home') }}</a></li>
            <li class="breadcrumb-item active"><a href="{{ route('tasks.index') }}">{{ __('admin.Tasks') }}</a></li>
            <li class="breadcrumb-item active">{{ __('admin.Show Task') }}</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
@endsection
@section('content')
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- jquery validation -->
          <div class="card card-primary">
            <div class="card-header">
              <h3>{{ __('admin.Show Task') }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="quickForm" method="POST" action="{{ route('tasks.show', $task->id) }}">
                @csrf
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                            <label for="name">{{ __('admin.Name') }}</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Enter name" value="{{ $task->name }}">
                            </div>
                            <div class="form-group ">
                                <label for="client">{{ __('admin.Projects') }}</label>
                                <select class="form-control" name="project_id" id="project_id">
                                    @foreach ($projects as $project)
                                        <option value="{{ $project->id }}" @if($project->id == $task->project_id) selected @endif>{{ $project->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group ">
                                <label for="due_date">{{ __('admin.Due Date') }}</label>
                                <input type="text" class="form-control datepicker" placeholder="Enter Due Date" name="due_date" id="due_date" autocomplete="off" value="{{ $task->due_date }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group ">
                                <label for="assigned_to">{{ __('admin.Assigned To') }}</label>
                                <select class="form-control" name="assigned_to" id="assigned_to">
                                    @foreach ($members as $member)
                                        <option value="{{ $member->id }}" @if($member->id == $task->member_id) selected @endif>{{ $member->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>{{ __('admin.Status') }}</label>
                                <select class="form-control" name="status" id="status">
                                    <option>{{ __('admin.Select') }}</option>
                                    <option value="active" {{ $project->status == 'active' ? 'selected' : '' }}>{{ __('admin.Active') }}</option>
                                    <option value="inactive" {{ $project->status == 'inactive' ? 'selected' : '' }}>{{ __('admin.Inactive') }}</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
          </div>
          <!-- /.card -->
          </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>

    $('.datepicker').datepicker({
        // format: 'yyyy-mm-dd',
        format: 'dd-mm-yyyy',
        startView: 2,
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true
    });
</script>
@endsection